### ISSUE TITLE
504 response with "jpm sign"

### ISSUE THREAD

**Issue by nikolas** [mozilla/olympia#1106]
I'm using jpm 1.0.4, node.js 4.2.1. I'm having trouble signing my extension:

$ jpm sign --api-key user:11079870:922 --api-secret >secret<
Creating XPI
JPM [info] XPI created at /tmp/tmp-unsigned-xpi-30579fW3n868y4lkq/@mediathread-firefox-0.1.1.xpi (175ms)
Created XPI at /tmp/tmp-unsigned-xpi-30579fW3n868y4lkq/@mediathread-firefox-0.1.1.xpi
JPM [info] Created XPI for signing: /tmp/tmp-unsigned-xpi-30579fW3n868y4lkq/@mediathread-firefox-0.1.1.xpi
JPM [error] FAIL
Error: Received bad response from the server while requesting https://addons.mozilla.org/api/v3/addons/%40mediathread-firefox/versions/0.1.1/

status: 504
response: 
headers: {"content-length":"0","connection":"Close"}

    at /home/nnyby/node_modules/jpm/lib/amo-client.js:85:13
    at tryCatchReject (/home/nnyby/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/home/nnyby/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/home/nnyby/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/home/nnyby/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/home/nnyby/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/home/nnyby/node_modules/when/lib/Scheduler.js:27:9)
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)

Also, now I can't upload my extension:
![2015-12-17-161041_535x564_scrot](https://cloud.githubusercontent.com/assets/59292/11882131/c442279a-a4d8-11e5-914a-69b109b55969.png)

**Comment by wagnerand** [comment]
What is the URL to your add-on?

**Comment by nikolas** [comment]
The URL is: https://addons.mozilla.org/en-US/developers/addon/mediathread

**Comment by wagnerand** [comment]
Background info: This add-on is listed.

**Comment by kumar303** [comment]
Hi @nikolas 

> Background info: This add-on is listed.

To elaborate on this, `jpm sign` will only put your new version in the queue when the add-on is listed. This is because listed add-ons still require manual review.

Also, this 504 indicates a problem with our server configuration but I can't find other evidence of this happening right now. Is the 504 still happening or did it go away?

**Comment by nikolas** [comment]
The 504 went away, and I am able to upload new versions.

I was confused, and thought `jpm sign` is now required for all XPIs in FF 43+ ( I found out that a xpi created with `jpm sign` still doesn't work: https://github.com/ccnmtl/mediathread-firefox/releases/tag/0.1.1)

I didn't realize that now we have to choose being "Listed" or "self-distributed" and can't do both. I find this really inflexible.. but anyways, I lost my review queue position 15 because I deleted version 0.1.0 (`jpm sign` told me the version already existed, so my reasoning was, delete the version, upload the new "jpm sign'ed" version).

I don't see these as technical problems with `jpm sign`, now that I think I understand it a little better. I would like to get back my queue position, since I'm now at 163.

**Comment by kumar303** [comment]
> I was confused, and thought jpm sign is now required for all XPIs in FF 43+

yes, that's true.

>  I found out that a xpi created with jpm sign still doesn't work: https://github.com/ccnmtl/mediathread-firefox/releases/tag/0.1.1)

This looks like it was created with `jpm xpi` not `jpm sign`. Also, since your add-on is listed you wouldn't be able to generate a signed add-on automatically.

> I didn't realize that now we have to choose being "Listed" or "self-distributed" and can't do both.

What were you trying to do exactly? Were you trying to distribute an add-on that some users could use before it was reviewed and available on addons.mozilla.org ? Were you trying to test your add-on in the release channel?

**Comment by nikolas** [comment]
> This looks like it was created with jpm xpi not jpm sign. Also, since your add-on is listed you wouldn't be able to generate a signed add-on automatically.

`jpm sign` actually did create this xpi. Here's the output log:

```
$ jpm sign --api-key user:11079870:922 --api-secret "secret"
Creating XPI
Creating XPI
JPM [info] XPI created at /tmp/tmp-unsigned-xpi-32345jbhlDzmn8RTh/@mediathread-firefox-0.1.1.xpi (173ms)
Created XPI at /tmp/tmp-unsigned-xpi-32345jbhlDzmn8RTh/@mediathread-firefox-0.1.1.xpi
JPM [info] Created XPI for signing: /tmp/tmp-unsigned-xpi-32345jbhlDzmn8RTh/@mediathread-firefox-0.1.1.xpi
JPM [error] Server response: Version already exists. ( status: 409 )
JPM [info] FAIL
```

> What were you trying to do exactly? Were you trying to distribute an add-on that some users could use before it was reviewed and available on addons.mozilla.org ? Were you trying to test your add-on in the release channel?

I was trying to make sure this addon is able to be distributed via my xpi file, in case the review hasn't completed in time (I was expecting to have users using this addon in a few weeks).

My goal was, stay in the addon review queue so my extension can be officially approved, but also have a backup plan (self-distribution).

So I just got frustrated because I'm at the back of the review queue again, but self-distribution isn't an option anymore unless I commit to *always* self-distribute this extension. It seems to be my only option if I want this extension usable in a few weeks, though.

**Comment by kumar303** [comment]
> jpm sign actually did create this xpi.

Oh, oops. This is a bug: https://github.com/mozilla-jetpack/jpm/issues/439 What happened is `jpm sign` first created an XPI from your source code but signing failed so it left the XPI in your directory (the unsigned one).

> My goal was, stay in the addon review queue so my extension can be officially approved, but also have a backup plan (self-distribution).

This isn't supported very well at the moment. What you'd have to do is create a separate ID, something like `mediathread-prerelease`. This would be easy to automate: just copy your source dir, change the ID in package.json, and run `jpm sign`. You wouldn't need to upload anything manually because by default `jpm sign` will create unlisted add-ons. It would show up in your Dev Hub list as a separate add-on and obviously wouldn't have any stats (because it would be self-distributed).

In the future we hope to support this case more directly. We're tracking this feature here: https://github.com/mozilla/olympia/issues/1066

**Comment by kumar303** [comment]
> The 504 went away, and I am able to upload new versions.

Based on this comment, I'm closing the issue. Thanks for the initial bug report, we're looking into better server stability.

**Comment by nikolas** [comment]
> This isn't supported very well at the moment. What you'd have to do is create a separate ID, something like mediathread-prerelease. This would be easy to automate: just copy your source dir, change the ID in package.json, and run jpm sign. You wouldn't need to upload anything manually because by default jpm sign will create unlisted add-ons. It would show up in your Dev Hub list as a separate add-on and obviously wouldn't have any stats (because it would be self-distributed).

Thanks for explaining this workaround. I'm just glad to have a way forward.
