### ISSUE TITLE
Add monitoring to make sure celery is connected to Sentry

### ISSUE THREAD

**Issue by kumar303** [mozilla/olympia#1120]
The upgrade to celery in https://github.com/mozilla/olympia/pull/678 broke the connection between celery and Sentry; it would be great to add monitoring so that this doesn't happen again. I'm not sure of the best way to monitor this but for reference, I added a [management test command](https://github.com/mozilla/olympia/blob/master/apps/zadmin/management/commands/gen_celery_error.py) and fixed the celery->Sentry hook up in  https://github.com/mozilla/olympia/pull/1119 .

**Comment by andymckay** [comment]
I don't think we have monitoring for any other part of this flow. You'd need to trigger an error and then ensure its in sentry at some X seconds later and do that in nagios through tunnels. 

I'd like to keep the management command around because that's a quick sanity check that celery error logging is working and that's valuable. But I don't see an easy way to do this or think it will happen.
