### ISSUE TITLE
Slow query in /browse.views:personas

### ISSUE THREAD

**Issue by andymckay** [mozilla/olympia#1224]
According to new relic:

``` SELECT COUNT(*) FROM `addons` WHERE ((?=?) AND NOT (`addons`.`status` = %s ) AND NOT (`addons`.`is_listed` = %s ) AND `addons`.`current_version` IS NOT NULL AND `addons`.`inactive` = %s  AND `addons`.`status` IN (%s) AND `addons`.`addontype_id` = %s  AND NOT (`addons`.`id` IN (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s))) ```

Approximately 250333 rows of this table were scanned.

```File "/data/olympia/apps/browse/views.py", line 349```

Thats a terrible statement inside in personas. Let's get that fixed.

**Comment by andymckay** [comment]
Not sure if this will work, but here's a link: https://rpm.newrelic.com/accounts/315282/applications/2799916/datastores#/overview/All/trace/?id=b0c8c6-eeeaed15-b4a7-11e5-8436-c81f66b8ceca&metric=Datastore%252Fstatement%252FMySQL%252Faddons%252Fselect

**Comment by andymckay** [comment]
Tracker #1244

**Comment by magopian** [comment]
So, I'm not sure what are the ways around this issue:
1/ running it less often: it should already be cached using django-cache-machine, but according to newrelic it's still run 2000 times per minute?! Is that the number of times this query is taken from the cache, or the number of times it's really run?
2/ getting rid of some functionality

Regarding 2/, here are the few things I believe are making the query slower:
- we're explicitly excluding frozen addons. According to new relic, there's 20 of them. Are we still using them? What are they for? Could we instead of having them in the DB, have them as a setting for example?
- we get the count to know exactly how many pages of themes we have in the paginator. Maybe we could only ever display the first 10 pages (that's what we already do for "up and coming"). Another idea would be to now display the links to all the pages, but only the first 10, and on the 10th page, if there's still a full batch of themes (we filled the current grid), then we can guess there's some more, and then display a "next" link in this case?
- we could have a cron (one more...) that runs every day (or hour?) to get the number of themes for each combination of category/sort, and then use that instead of computing the count each and every time
- use ES? There's a comment from @kumar303 about that [here](https://github.com/mozilla/olympia/blob/ed242718220171a4da94ba41e4b7e1bd8e690424/apps/addons/views.py#L334) that seems related to the frozen addons performance hit

Ideas? Suggestions? ping @andymckay @kumar303 @diox

**Comment by diox** [comment]
New relic shows the number of times the query ran in MySQL. cache-machine intercepts it at a higher level. The usual call count is pretty low, but it appears sometimes we suffer from a classic [thundering herd problem](https://en.wikipedia.org/wiki/Cache_stampede) and get lots of calls in a very short period of time. We could try using cache backends designed to alleviate this, although cache-machine has its own expiry mechanism for counts, so we should be careful here.

Note that from new relic, it appears that the update_addons_current_version crons/task is a big caller, and we want to remove that cron - see #1242.

**Comment by diox** [comment]
Regarding changing functionality. I'd be in favor of using ES everywhere on the frontend :) But apart from that, switching to an infinite paginator that does not do a count, with an optional limit to the maximum number of pages shown, would solve the problem entirely. Or yeah, a cron to update a count every hour like you said.

**Comment by diox** [comment]
Couple more things about this query btw:
- It's filtering on addons.status twice
- It's filtering on `is_listed`, which is not in the index it's using
- The estimate row count (which the mysql query optimizer depends on to determine which index to use) is really wrong - not having an accurate number is normal, but this is quite far from reality.

**Comment by andymckay** [comment]
We'll do this in the rewrite.
