### ISSUE TITLE
[AMO-Dev] Review cannot be edited

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1277]
Steps to reproduce:
1. Load AMO-dev page https://addons-dev.allizom.org/en-US/firefox/
2. Go to any add-on details page (i.e. https://addons-dev.allizom.org/en-US/firefox/addon/google-search-link-fix/)
3. Write a review
4. Edit the review and submit the changes

Expected results:
The changes are saved. The review is modified.

Actual results:
Nothing happens.

Notes/Issues:
There is a js error displayed in the console.
Please see the screenshot: 
![2016-01-08_1607](https://cloud.githubusercontent.com/assets/15685960/12200118/bfb4ba36-b625-11e5-9ebc-bc7f79c6769e.png)
Verified on AMO-dev FF43(Win 7).
Tracker issue: #1197

**Comment by muffinresearch** [comment]
Yep - this one is due to http://jquery.com/upgrade-guide/1.9/#jquery-ajax-returning-a-json-result-of-an-empty-string 

Seems to be a single isolated view returning a standard HttpResponse in a @json_view. Can't seem to see any other @json_view decorated code that matches the same issue.

https://github.com/mozilla/olympia/blob/master/apps/reviews/views.py#L269

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF43(Win 7).
Postfix screencast: http://screencast.com/t/NqjITrfHEme
