### ISSUE TITLE
Submission incorrectly fails even if application info is specified in the manifest.json

### ISSUE THREAD

**Issue by krupa** [mozilla/olympia#1338]
## steps to reproduce:
1. Upload the webextension available at http://cl.ly/1t1G3z0g1U3z
2. After validation is successful, click Continue

## expected behavior:
User is able to proceed with the submission

## actual behavior:
Submission fails with "Need at least one platform."

Notice that gecko application is specified in the manifest.json @  https://pastebin.mozilla.org/885650

**Comment by magopian** [comment]
After investigation, it's because the manifest.json contains an invalid maximum version number (`50.*` doesn't exist on -dev, stage or prod: https://addons.allizom.org/en-US/firefox/pages/appversions/).

In the case of a "legacy" extension, the validator catches that and displays the following error message:
<img width="716" alt="screen shot 2016-01-13 at 11 12 21" src="https://cloud.githubusercontent.com/assets/167767/12291270/8d26156e-b9e6-11e5-92c2-8cace6fda38b.png">

However, in the case of WebExtensions, the validator doesn't catch this issue. There's two ways to go about that:
1/ catch this issue on olympia: I'm not sure that's what we want, we're not doing it for legacy extensions, as we're relying on the amo-validator, it would be strange to have such a hack in olympia just for that
2/ catch this issue in the amo-validator

@andymckay what do you think? Should we create an issue for that on the amo-validator and close this one?

**Comment by andymckay** [comment]
Sounds good to me.

**Comment by magopian** [comment]
Created https://github.com/mozilla/amo-validator/issues/385, closing this one now.
