### ISSUE TITLE
Slow query in theme_user_counts

### ISSUE THREAD

**Issue by andymckay** [mozilla/olympia#1365]
```
# Query_time: 87.684466  Lock_time: 0.000058 Rows_sent: 930266  Rows_examined: 372876507
use addons_mozilla_org;
SET timestamp=1452615631;
SELECT `theme_user_counts`.`id` FROM `theme_user_counts` WHERE `theme_user_counts`.`date` = '2016-01-11'  ORDER BY `theme_user_counts`.`date` DESC;
# Time: 160112 16:22:31
```

Rows examined 372876507? That's a lot of rows. Tracker: #1244

**Comment by diox** [comment]
This query is made by the `index_stats` management command which is called every day by the `index_latest_stats` cron to index statistics about a few things in ES. The stats views then use the data from ES exclusively, via `<model>.search()`.

The query does use a `addon_date_idx` index, which is a composite index on (`addon_id`,`date`). But because this index has `addon_id` first, it's not that useful to us here. 

The management command has different options that can cause it to filter by addons (with or without the date), but it doesn't do it by default, and it does not do it in the cron called every day. So I recommend changing the index to just index by date.

The same index already exists in `download_counts` and `update_counts`, at least, which are used in a similar fashion. I'm going to spend some time looking at those to see if they'd benefit from changing the index as well.

**Comment by andymckay** [comment]
Should go away in #1395
