### ISSUE TITLE
Investigate using a different database for stats operations

### ISSUE THREAD

**Issue by diox** [mozilla/olympia#1428]
To prevent statistics cron jobs from hammering the master db, it'd be nice to see if we can split everything related to stats to a different database, even for writes.

We need a better picture of how and where stats are used first. I'm compiling that in this gist: https://gist.github.com/diox/891dbbd940dc7839431c

Supports #1395

**Comment by andymckay** [comment]
We spoke about this in the meeting where it was described as "tricky". There are multiple problems here including schematic and the ability to write into multiple databases at once (since the primary database needs to be updated). I was hoping that this would be an easy win, but sounds like it isn't. Let's see how much the archiving of data and improving some indexes helps.

Tracker: #1395
