### ISSUE TITLE
Restrict most recent review submissions for users in a particular group

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/olympia#1443]
There are a couple of extremely active add-on reviewers who tend to grab the easiest (and most recent) reviews in the queue as soon as they appear, which limits the options available for new reviewers. This stunts our ability to grow and diversify the reviewer team.

We want to create a user group (say, "Limited Reviewers") for which all add-ons in the review queues waiting for under 20 hours are hidden. Blocking the review submission form for those add-ons would also be good.

**Comment by wagnerand** [comment]
I'm going to give this a try.

**Comment by andymckay** [comment]
This seems counter intuitive to me, we are making AMO and the reviewer tools more complicated to solve a problem of active reviewers. The fact that we are making things more complicated is a red flag to me at the moment and doing it to solve a social problem (can we just ask them not to) makes it even worse in my mind.

**Comment by jvillalobos** [comment]
We already tried asking, and it didn't work. We also don't want to lose our most active reviewers over this.

**Comment by erosman** [comment]
@andymckay 

When I joined AMO, the queues were over 850 entries long.
When we stopped reviewing and went to London MozFest in 2014, the queues went back to around 650.

It has been 1.5 years since the discriminatory action.

The result, as expected, has been counter-productive. Queues soared from near zero to over 850.
It caused a GREAT deal of resentments from the developers who had to wait months for a review.

The premise of making new addons available to new reviewers, may have sounded reasonable to some but in reality, all it did was to alienate the most active users.

I cut down my reviews to less than half (I used to do up to 1400 per month for free as a volunteer).

Where are the promised new reviewers that were cited as the reason for the discrimination?

Since I have joined, we have received 100s of "welcome new reviewer" emails but where are they now?

They all have left, even with the above mentioned discriminatory action in place.


https://blog.mozilla.org/addons/2016/03/04/breakthroughs-in-the-add-on-review-queues/
https://blog.mozilla.org/addons/2015/09/04/turning-the-queues-around-new-forum/

_discrimination: the unjust or prejudicial treatment of different categories of people or things_

**Comment by jvillalobos** [comment]
The introduction of the restriction (week 4 in the chart) actually helped increase contributions by other reviewers. However, overall contributions dropped later in the year and didn't recover. The reasons for this are varied and this restriction wasn't the sole contributor.
![image](https://user-images.githubusercontent.com/62568/27296135-e7df1f22-54dc-11e7-8216-c6c47315b206.png)
We're moving to a different review process in part so we are not as dependent on volunteer reviewer availability. In that process this restriction won't be needed anymore, so we will eventually remove it.

**Comment by erosman** [comment]
As your graph shows, the effect of discrimination benefited others for a WHOLE ONE WEEK and then nothing. However, you kept the restriction in-place for 1.5 years and running.

On a number of occasions I had to tell developers that I cant review their addons since they were not available to me.

It was quite obvious from the start what the outcome would be. ;)

**Comment by erosman** [comment]
@andymckay @caitmuenster 

**On reflection, the fact that the discrimination was introduced and kept in place for 1.5 years (and running) even-though it had no merit, clearly demonstrates that the purpose of the measure was merely to discriminate.**

If Mozilla has a department dealing with Discrimination and Racial Equality, they should investigate the aforementioned practices.

**Comment by caitmuenster** [comment]
Hi @erosman. I'm going to echo Jorge's comment that this restriction will be removed in a few weeks when we transition to the post review process. 

In the meantime, I'd like to refer you to Mozilla's [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) for information about contacting the Diversity & Inclusion team.

**Comment by erosman** [comment]
@caitmuenster 

I understand that the new changes will change everything. However, that does not justify the discrimination of the last 1.5 years (for no reason at all), neither does it answer the concerns raised.
