### ISSUE TITLE
sign invalid addons so we can run tests in automation

### ISSUE THREAD

**Issue by kmoir** [mozilla/olympia#1515]
I'm working on helping the developer productivity team run some try runs running our tests with signed addons.  This is to prepare for when we run tests on branches where the signed addon preference is enabled by default.  Recently, I was talking to kumar in #amo and was mentioning some of my problems where we need to have addons signed so the tree doesn't show up as red when the pref is enabled.  However, many of these addons are invalid so we can test scenarios.  He advised me to open an issue for this since the addon validation doesn't sign invalid addons.  I attached a zip of addons that were problematic

[baddons.zip](https://github.com/mozilla/olympia/files/103655/baddons.zip)

#bad
corrupt.xpi
corruptfile.xpi
empty.xpi
#bad id
multi_badid.xpi
#empty id in install.rdf
multi_broken.xpi
multi_signed.xpi
#Error: ID was empty in install.rdf
multi_unsigned.xpi
#version already exists
test_bug526598_2.xpi
#did not get signed
test_bug526598_1.xpi

**Comment by kumar303** [comment]
Well, huh, this might be tricky. I'll work on this to see if we can come up with something.

**Comment by andymckay** [comment]
@jasonthomas can sign add-ons directly I believe against trunion. Given that these are broken and should never go through validator, that might be our best bet.

**Comment by kumar303** [comment]
The signing will be done with this FYI https://github.com/jasonthomas/sign-addon

**Comment by kumar303** [comment]
We also discussed the end goal for releng in IRC. They need to protect against regressions in code that handles corrupted add-ons. Since signed add-ons are required in the real world, it won't be as easy to install corrupted add-ons -- thus, running these tests with the default prefs might not be helpful. One idea presented was to run all these regression tests on the non-public build which would still accomplish the goal of catching code regressions.

**Comment by kmoir** [comment]
We visited this issue earlier in the project and we don't want to have a second set of builds running tests for unsigned addons in automation.  We thought there were security issues with this approach and a lot of duplicated content/load on our CI farm for little benefit.  I added this topic as a discussion item for the next addons meeting :-)

**Comment by jasonthomas** [comment]
[baddons-signed.zip](https://github.com/mozilla/olympia/files/104102/baddons-signed.zip)

I've signed the ones that I could, which were test_bug526598_1.xpi, test_bug526598_2.xpi and empty.xpi. The empty.xpi was signed by providing a guid (I used 'empty@tests.mozilla.org) since it was just a empty file.

I didn't try to sign the mutl package since only the inner add-ons need to be signed https://github.com/mozilla/olympia/blob/12f806169a5b62e79ccf1e7fa88ee7e609dd173b/lib/crypto/packaged.py#L128
