### ISSUE TITLE
CSP error in about:addons

### ISSUE THREAD

**Issue by kewisch** [mozilla/olympia#1555]
I'm getting this message in the Thunderbird 38 error console, I guess because about:addons is open:

> Error: Content Security Policy: The page's settings observed the loading of a resource at https://addons.mozilla.org/en-US/thunderbird/jsi18n.js?b=01ef2c4-56a7a899 ("script-src https://services.addons.mozilla.org https://www.paypalobjects.com https://apis.google.com https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://ssl.google-analytics.com https://addons.cdn.mozilla.net"). A CSP report is being sent.

Relates to #995

**Comment by muffinresearch** [comment]
@kewisch thanks - that's a good catch. 

The cause is that about:addons uses a different domain; the value of 'self' in CSP here is https://services.addons.mozilla.org and not https://addons.mozilla.org/ so the latter is being blocked.

**Comment by muffinresearch** [comment]
Removing the blocks-release since csp will remain in report-only for a bit longer.

**Comment by muffinresearch** [comment]
The fix for this will be in production this Thursday.

**Comment by muffinresearch** [comment]
QA notes:

This should be testable on -dev and stage with the following disco pane hosts:

dev: https://addons-dev-services.allizom.org/
stage: https://addons-services.allizom.org/

**Comment by krupa** [comment]
When I load Tools-> Add-ons (pointing to dev), I see the promo module failing to load

CSP errors:

Content Security Policy: The page's settings blocked the loading of a resource at https://addons-dev.allizom.org/en-US/firefox/discovery/pane/account ("connect-src https://addons-dev-services.allizom.org https://sentry.prod.mozaws.net"). <unknown>
Content Security Policy: The page's settings blocked the loading of a resource at https://addons-dev.allizom.org/en-US/firefox/discovery/pane/promos/47.0a1/Darwin ("connect-src https://addons-dev-services.allizom.org https://sentry.prod.mozaws.net").

screenshot:
https://www.dropbox.com/s/q0ywyoplvhlydip/Screenshot%202016-02-03%2017.09.36.png?dl=0

Since the issue summary refers to CSP errors in about:addons i just reopened this one even though it is a different error.

**Comment by muffinresearch** [comment]
I think this might be a configuration difference between -dev and stage. I'll look into it.

**Comment by muffinresearch** [comment]
Yep this is a config difference which explains why it's not seen on production.

For -dev it seems that the XHR requests are made to addons-dev.allizom.org which doesn't match 'self' for connect-src in the CSP config. However in production XHR requests are going via services.addons.m.o which does match 'self' which is why there's no warning for prod.

I think these can safely be ignored as they're not occuring in production, however it would be nice to change the setup for -dev and stage to be a better match to whatever we're doing in production.

@jasonthomas do we run different settings for services in prod?

**Comment by jasonthomas** [comment]
Yes, the SERVICES_URL on dev and stage were configured to SITE_URL. PR open to fix this.

**Comment by muffinresearch** [comment]
Ah brilliant, thanks jason.

**Comment by muffinresearch** [comment]
@krupa ok with the settings update in place this should be fixed now for -dev if you'd like to re-try.

**Comment by muffinresearch** [comment]
Going to close this on the basis that all issues should be resolved.

**Comment by krupa** [comment]
verified.
