### ISSUE TITLE
[CSP] violation in Statistics page when switching through "For last" menu options

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/olympia#1577]
Relates to #995

Steps to reproduce:
1. Load Statistics page for an add-on with public stats (i.e. https://addons.mozilla.org/en-US/firefox/addon/firebug/statistics/)
2. Switch through "For last" menu options with web console opened (!Security tab)

Expected results:
There is no CSP violation in the console.

Actual results:
There is a CSP violation displayed in the console every time "For last" menu option are changed.

Notes/Issues:
Please see the csp reporting via network: https://pastebin.mozilla.org/8858313
Verified on FF44(Win 7). Issue is reproducing on AMO-prod.
Screenshot for this issue: 
![2016-02-02_1117](https://cloud.githubusercontent.com/assets/15685960/12745230/ea5d8bc6-c9a0-11e5-8823-e08a36a34036.png)

**Comment by muffinresearch** [comment]
At first this looks like prefetching. But actually it seems to be reproducible only with a empty cache. Clicking about on the last links there's a request made for the previous page. Also whilst this looks to be tripping something similar to the prefetch problem we don't have any explicit prefetching afaict.

I'm investigating to try and see what the problem is. I suspect it might be related to history state.

**Comment by muffinresearch** [comment]
The problem appears to be related to this line: https://github.com/mozilla/olympia/blob/master/static/js/impala/stats/stats.js#L21 which seems to be causing a request.

**Comment by andymckay** [comment]
Blocks #995

**Comment by muffinresearch** [comment]
So I've been digging into this and it would appear that there's some kind of implicit prefetching going on caused by the replaceState change. If the url is changed to just be a fragment identifier then no request is made which would make sense to some degree since fragment ids are never sent to the server.

Seems to be only easily repro'd when you hard refresh the initial page. The prefetch setting in `about:config` makes no difference either. 

I found this resource which appears to outline some correlation between prefetching and history api interactions. https://github.com/nickhsharp/prefetchNightmare

As it stands there doesn't look to be anything that we can do this end. 

What we should do is test this out on stage next week once CSP is fully enabled. But I suspect that it won't have any impact, and it will just be noise in the console and the CSP reports.

**Comment by muffinresearch** [comment]
Actually I just had a thought. We might be able to get around this problem if default-src was set to 'self'. I'm going to test that theory out.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![2016-03-14_1247](https://cloud.githubusercontent.com/assets/15685960/13742186/17ddf754-e9e3-11e5-8f91-cacaf833972b.png)

There is a js warning but I suppose is not important and for sure is not related to this.
@muffinresearch ,  let me know if I should do something in what concerns this.
