### ISSUE TITLE
Do not localize add-on deletion emails

### ISSUE THREAD

**Issue by wagnerand** [mozilla/olympia#909]
https://github.com/mozilla/olympia/blob/master/apps/addons/models.py#L458 sends emails when an add-on is being deleted. The property `atype` is being localized. We don't want that as it makes it very hard to search in those emails.

I'd give a shot a this myself, but I don't know why l10n happens in the first place. Any hints are appreciated.

Example:
`The following ΘΈΜΑ was deleted.`

**Comment by andymckay** [comment]
Because the locale of the email is set to the person deleting. ADDON_TYPE is localised here: https://github.com/mozilla/olympia/blob/master/apps/constants/base.py#L161-L172

What you want to do is make everything in the email be in en-US. There is an `activate_lang` context manager on the user that does something very similar to this. What might work is to make that accept an argument and then do something like: 

```
with request.user.activate_lang('en-US'):
   ... send email
```

Then after the email has been sent, everything will continue in the users locale.

**Comment by wagnerand** [comment]
Thanks Andy, that was very helpful!

Looks like `activate_lang` already accepts an argument to pass the target language, yay!

**Comment by wagnerand** [comment]
Prerequisites:
```
--- a/apps/amo/utils.py
+++ b/apps/amo/utils.py
@@ -164,6 +164,9 @@ def send_mail(subject, message, from_email=None, recipient_list=None,
     from amo.tasks import send_email
     import users.notifications as notifications

+    import ipdb; ipdb.set_trace()
+
     if not recipient_list:
         return True
```

How to test the patch:

1) Set the default locale in your user profile to a language that you know has the word "extension" localized, e.g. "German".
2) Upload a new add-on
3) Go to the developer hub -> Status and Versions
4) Delete your add-on.

When ipdb pauses, inspect `subject` or `message`.

**Comment by magopian** [comment]
Here are STRs that don't require modifying the code:
1/ set your locale to be something different than english (eg german)
2/ go to the devhub and delete the add-on
3/ check the "fake mails" (using `/en-us/admin/mail`): the mail subject and content should contain something like `Deleting EXTENSION <extension> (<extension id>)`: the `EXTENSION` word shouldn't be localized (and nothing else should be localized either)
