### ISSUE TITLE
AMO prod updates are applied with a delay

### ISSUE THREAD

**Issue by vcarciu** [mozilla/olympia#913]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0

Steps to reproduce:
1.Perform any action which should add a visual modification on AMO prod (ie. add many reviews to an app, follow\unfollow a collection, add a new addon to a collection)
2.Refresh the page to see the changes

Expected results:
AMO is instantly updated

Actual results:
Strange behaviors are seen after refresh (ie. reviews disappear , followed collections are still seen as unfollowed , addons are not added to collections, etc... )

I added two screencast with these issues:
http://screencast.com/t/orqXjzTZ
http://screencast.com/t/yC3T21BF82

**Comment by vcarciu** [comment]
This is not reproducible on Stage

**Comment by kumar303** [comment]
For context, this is how the code is expected to work:

* user performs an action that causes a DB write (such as submitting a review)
* they get a cookie that [pins them to the master MySQL DB](https://github.com/jbalogh/django-multidb-router/blob/75f0b6bc7745e5c0a728b5d44940237361e46c61/multidb/middleware.py) for 15 seconds
* each subsequent request should get data from the master DB instead of a slave DB
* this prevents them from seeing any noticeable lag

Some theories:
* maybe 15 seconds is too short on AWS and we need to increase it. We're still trying to find evidence of laggy slaves or not.
* maybe django-cache-machine is involved? That deals with selecting data from memcache instead of the db. Not sure if it's related though.

**Comment by muffinresearch** [comment]
This is causing problems with login related to new users see #917 - ops are investigating.

**Comment by kumar303** [comment]
Update: @jasonthomas increased the size of redis and the cache lag seems to have gone away. That is, I can no longer reproduce the add/delete/refresh test on the review page. This suggests that the key flush lists which were [stored in redis](https://github.com/washort/django-cache-machine/blob/4690198122a96a88267323566dc18a5e0437681f/caching/invalidation.py#L163) were getting evicted *before* the associated memcache keys were evicted, resulting in memcache keys that never got flushed. Redis is at version 2.8.23 and is currently configured for [volatile-lru](http://redis.io/topics/lru-cache#eviction-policies). Jason is monitoring it and we'll have to see if the problems come back once the larger redis instance hits its max memory.

**Comment by kumar303** [comment]
Thanks for verifying. I am skeptical that this is actually fixed :) But we'll see what happens when the larger redis instance hits its memory max and has to start evicting the cache. We can always re-open though.
